### PR TITLE
Remove all appended dom when `destroyAll` called

### PR DESCRIPTION
**Pull request by hq5544**
Our team use pulltorefresh.js recently.
We found that when `destroyAll` called, ptr dom appended won't be removed. I think it is not intuitive.
So I add this PR.

### CODE REVIEW

**Comment by pateketrueke** [comment]
I think we could collect all added nodes to the DOM and dettach'em all at once, instead of adding attributes and selecting'em before, etc.

**Comment by hq5544** [comment]
While, if I import two pulltorefresh.js in different files, and initialise them. A and B.We may not get all the

**Comment by faelsoto** [comment]
I don't think including two instances of the same library is a standard use case. The PR is welcome, but what @pateketrueke is saying is that there are better ways to reference the objects created than setting a dataset value.

**Comment by hq5544** [comment]
Yes, I got it. Thanks.

**Comment by faelsoto** [comment]
Well, there's no need to close it, you could contribute something following the project's standards.

**Pull request closed without merging**
